// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: lobby_service_grpc.proto

#include "lobby_service_grpc.pb.h"
#include "lobby_service_grpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace lobby_service {

static const char* LobbyService_method_names[] = {
  "/lobby_service.LobbyService/RegisterServer",
  "/lobby_service.LobbyService/Ping",
};

std::unique_ptr< LobbyService::Stub> LobbyService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LobbyService::Stub> stub(new LobbyService::Stub(channel, options));
  return stub;
}

LobbyService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegisterServer_(LobbyService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Ping_(LobbyService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LobbyService::Stub::RegisterServer(::grpc::ClientContext* context, const ::lobby_service::RegisterServerRequest& request, ::lobby_service::RegisterServerReponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::lobby_service::RegisterServerRequest, ::lobby_service::RegisterServerReponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterServer_, context, request, response);
}

void LobbyService::Stub::async::RegisterServer(::grpc::ClientContext* context, const ::lobby_service::RegisterServerRequest* request, ::lobby_service::RegisterServerReponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::lobby_service::RegisterServerRequest, ::lobby_service::RegisterServerReponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterServer_, context, request, response, std::move(f));
}

void LobbyService::Stub::async::RegisterServer(::grpc::ClientContext* context, const ::lobby_service::RegisterServerRequest* request, ::lobby_service::RegisterServerReponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterServer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::lobby_service::RegisterServerReponse>* LobbyService::Stub::PrepareAsyncRegisterServerRaw(::grpc::ClientContext* context, const ::lobby_service::RegisterServerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::lobby_service::RegisterServerReponse, ::lobby_service::RegisterServerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterServer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::lobby_service::RegisterServerReponse>* LobbyService::Stub::AsyncRegisterServerRaw(::grpc::ClientContext* context, const ::lobby_service::RegisterServerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterServerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LobbyService::Stub::Ping(::grpc::ClientContext* context, const ::lobby_service::PingRequest& request, ::lobby_service::PingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::lobby_service::PingRequest, ::lobby_service::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void LobbyService::Stub::async::Ping(::grpc::ClientContext* context, const ::lobby_service::PingRequest* request, ::lobby_service::PingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::lobby_service::PingRequest, ::lobby_service::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void LobbyService::Stub::async::Ping(::grpc::ClientContext* context, const ::lobby_service::PingRequest* request, ::lobby_service::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::lobby_service::PingResponse>* LobbyService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::lobby_service::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::lobby_service::PingResponse, ::lobby_service::PingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::lobby_service::PingResponse>* LobbyService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::lobby_service::PingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

LobbyService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LobbyService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LobbyService::Service, ::lobby_service::RegisterServerRequest, ::lobby_service::RegisterServerReponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LobbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::lobby_service::RegisterServerRequest* req,
             ::lobby_service::RegisterServerReponse* resp) {
               return service->RegisterServer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LobbyService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LobbyService::Service, ::lobby_service::PingRequest, ::lobby_service::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LobbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::lobby_service::PingRequest* req,
             ::lobby_service::PingResponse* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
}

LobbyService::Service::~Service() {
}

::grpc::Status LobbyService::Service::RegisterServer(::grpc::ServerContext* context, const ::lobby_service::RegisterServerRequest* request, ::lobby_service::RegisterServerReponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LobbyService::Service::Ping(::grpc::ServerContext* context, const ::lobby_service::PingRequest* request, ::lobby_service::PingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace lobby_service

