// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf C++ Version: 5.29.3

#include "types.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace types {
}  // namespace types
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_types_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_types_2eproto = nullptr;
const ::uint32_t TableStruct_types_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_types_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013types.proto\022\005types\032 google/protobuf/de"
    "scriptor.proto*\264\001\n\010protocol\022\014\n\010kInvalid\020"
    "\000\022\013\n\006kHello\020\201 \022\r\n\010kPingReq\020\202 \022\r\n\010kPingRe"
    "s\020\203 \022\025\n\020kContentReadyReq\020\204 \022\025\n\020kContentR"
    "eadyRes\020\205 \022\021\n\014kHelloClient\020\206 \022\021\n\014kHelloS"
    "erver\020\207 \022\033\n\026kDisconnectAlertNotify\020\210 *s\n"
    "\006Result\022\014\n\010kSuccess\020\000\022\014\n\010kUnknown\020\001\022\023\n\017k"
    "InvalidRequest\020\002\022\025\n\021kInvalidParameter\020\003\022"
    "\r\n\tkNotFound\020\004\022\022\n\016kInternalError\020\005:H\n\nme"
    "ssage_id\022\037.google.protobuf.MessageOption"
    "s\030\351\007 \001(\0162\017.types.protocol\210\001\001b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_types_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_types_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_types_2eproto = {
    false,
    false,
    436,
    descriptor_table_protodef_types_2eproto,
    "types.proto",
    &descriptor_table_types_2eproto_once,
    descriptor_table_types_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_types_2eproto::offsets,
    file_level_enum_descriptors_types_2eproto,
    file_level_service_descriptors_types_2eproto,
};
namespace types {
const ::google::protobuf::EnumDescriptor* protocol_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_types_2eproto);
  return file_level_enum_descriptors_types_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t protocol_internal_data_[] = {
    65536u, 524288u, 4101u, 4099u, 4103u, 4098u, 4100u, 4102u, 4104u, 4097u, };
bool protocol_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, protocol_internal_data_);
}
const ::google::protobuf::EnumDescriptor* Result_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_types_2eproto);
  return file_level_enum_descriptors_types_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t Result_internal_data_[] = {
    393216u, 0u, };
bool Result_IsValid(int value) {
  return 0 <= value && value <= 5;
}
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::MessageOptions, ::_pbi::EnumTypeTraits< ::types::protocol, ::types::protocol_IsValid>,
                            14, false>
            message_id(kMessageIdFieldNumber, static_cast< ::types::protocol >(0));
// @@protoc_insertion_point(namespace_scope)
}  // namespace types
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_types_2eproto),
        ::_pbi::ExtensionSet::RegisterEnumExtension(
            &::google::protobuf::MessageOptions::default_instance(), 1001, 14,
            false, false, ::types::protocol_IsValid),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
