version: '3.0'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPass1!
    ports:
      - "1433:1433"
    restart: unless-stopped