server:
  port: "8080"

logging:
  level: "info"
  format: "json"
  
redis:
  address: "localhost:6379"
  password: "redis_dev"
  db: 0

mongodb:
  connstr: "mongodb://root:1234@localhost:27017"
  accountdb: "accountdb"

auth-provider:
  temp-session-expiry-seconds: 300
  google:
    client-id: 115847244815-vc7451712git8cu7snkkj8nkbfs784ci.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: "http://localhost:8080/auth/google/callback"
    userinfo-api-uri: "https://www.googleapis.com/oauth2/v2/userinfo"
    scopes:
      - "openid"
      - "email"
      - "profile"