services:
    coa-web-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: coa-web-app
        container_name: coa-web-app
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            - GIN_MODE=release
            - MONGODB_CONN_STRING=mongodb://root:1234@mongodb:27017
            - REDIS_ADDRESS=redisdb:6379
        depends_on:
            - mongodb
    redisdb:
        image: redis
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=redis_dev
        command: ["redis-server", "--requirepass", "redis_dev"]
        volumes:
        - redis_data:/data
    mongodb:
        image: mongo
        container_name: mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=1234
        volumes:
            - mongodb_data:/data/db
        healthcheck:
            test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 3
    db-viewer:
        image: mongo-express
        container_name: mongo-express
        restart: unless-stopped
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
            - ME_CONFIG_MONGODB_URL=mongodb://root:1234@mongodb:27017/?authSource=admin
            - ME_CONFIG_BASICAUTH_ENABLED=false
        depends_on:
            - mongodb
volumes:
    mongodb_data:
    redis_data: